chat/urls.py
from django.urls import path

from . import views
from .views import RoomView, ChatListView

urlpatterns = [
    # For page render
    path("", views.chat_list_render, name="index"),
    path("room/<int:store_id>", views.chatroom_render, name="room"),
    # For communication
    path("list", ChatListView.as_view(), name="ChatListView"),
    path("list/<int:goods_id>", ChatListView.as_view(), name="ChatListView"),
    path("room-connect/<str:store_id>", RoomView.as_view(), name="room"),
    # path("<str:store_id>/<str:user_id>/", RoomView.as_view(), name="room"),
]

oversea_backend/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    # path('', RedirectView.as_view(url='/user/intro', permanent=False)),
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("store/", include("store.urls")),
    # path("chat/", include("chat.urls")),
    path("restaurants/", include("restaurant2.urls")),
    path("", include_docs_urls(title="OverSea APIs") ),
    path(
        "schema",
        get_schema_view(
            title="OverSea APIs",
            description="APIs for Humascot OverSea",
            version="1.0.0",
        ),
        name="openapi-shecma",
    ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from users import views

app_name = 'users'

urlpatterns = [
    path("", views.UserListView.as_view(), name='user-list'),
    path("<int:pk>", views.UserDetailsView.as_view(), name='user-details'),
    path("current", views.CurrentUserView.as_view(), name='current-user'),
    path('users/<int:id>/delete/', views.UserDetailsView.as_view(), name='user-delete'),

    # join the membership
    path("signup", views.SignupView.as_view(), name="signup"),
    path("seller-signup", views.SellerSignup.as_view(), name="seller_google_signup"),
    # Restaurant
    path("signup-restaurant", views.RestaurantSignupView.as_view(), name="signup-restaurant"),
    path("signin-restaurant", views.RestaurantLoginView.as_view(), name="signin-restaurant"),
     path("signup-employee", views.EmployeeSignupView.as_view(), name="signup-employee"),
    path("signin-employee", views.EmployeeLoginView.as_view(), name="signin-employee"),
    # Manage superuser
    path('create-superuser', views.CreateSuperuserView.as_view(), name='create-superuser'),
    path('admin-users', views.ListAdminUsersView.as_view(), name='list-admin-users'),
    path('admin-users/<int:user_id>/get', views.GetAdminUserByIdView.as_view(), name='get-admin-user-by-id'),
    path('admin-users/<int:user_id>', views.DeleteAdminUserView.as_view(), name='delete-admin-user'),
    path('admin-users/<int:user_id>/update', views.UpdateAdminUserView.as_view(), name='update-admin-user'),
    # Manage client user
    path('client-users', views.ListClientUsersView.as_view(), name='list-client-users'),
    path('client-users/<int:user_id>/get', views.GetClientUserByIdView.as_view(), name='get-client-user-by-id'),
    path('client-users/<int:user_id>', views.DeleteClientUserView.as_view(), name='delete-client-user'),
    # Manage Seller user
    path('seller-users', views.ListSellerUsersView.as_view(), name='list-seller-users'),
    path('seller-users/<int:user_id>/get', views.GetSellerUserByIdView.as_view(), name='get-seller-user-by-id'),
    path('seller-users/<int:user_id>', views.DeleteSellerUserView.as_view(), name='delete-seller-user'),
    # Email Authentication
    path("send-email", views.SendEmail.as_view(), name="send_email"),
    path("check-email", views.CheckEmailView.as_view(), name="check_email"),
    # social login
    path("social", views.SocialUrlView.as_view(), name="social_login"),
    path("google", views.GoogleLoginView.as_view(), name="google_login"),
    # log in
    path("signin", views.LoginView.as_view(), name="signin"),
    path("check-token", views.CheckToken.as_view(), name="CheckToken"),
    # User information related
    path("my-page", views.UserView.as_view(), name="my_page"),
    path("my-page/profile", views.ChangeUserProfile.as_view(), name="ChangeUserProfile"),
    # page render
    path("page", views.my_page_render, name="my_page_render"),
    path("find", views.find_password_render, name="find_password_render"),
    path("more", views.more_page_render, name="more_page_render"),
    path("profile", views.user_profile_render, name="user_profile_render"),
    path("change-seller", views.change_seller_render, name="change_seller_render"),
    path("intro", views.intro_render, name="intro_render"),
    path("terms", views.term_render, name="intro_render"),
    path("policy", views.policy_render, name="intro_render"),
]

users/views.py
import base64
import os
import random
import string

import pytz
from django.db import transaction
from django.http import JsonResponse
from PIL import Image
import io
import requests
from django.core.files.base import ContentFile
import requests
from datetime import datetime

from django.contrib.auth.hashers import check_password
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404, redirect
from drf_yasg.utils import swagger_auto_schema
from google.oauth2 import id_token as google_id_token
from rest_framework import status, generics, permissions
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import RefreshToken
from rest_framework_simplejwt.views import TokenObtainPairView

from store.models import StoreModel
from store.serializers import (
    OnlyStoreInfoSerializer,
)
from .form import UserForm
from .models import CheckEmail, UserModel
from .serializers import (
    UserSerializer,
    LoginSerializer,
    SellerSerializer,
    PostUserSerializer,
    GetUserSerializer,
    AdminUserSerializer,
    ClientUserSerializer,
    SellerUserSerializer,
    RestaurantSerializer,
    EmployeeSerializer,
)
from django.shortcuts import render
import smtplib
import jwt
from django.conf import settings
from rest_framework import generics, permissions
from restaurant2.models import Restaurant, Employee


# Send email
class SendEmail(APIView):
    @swagger_auto_schema(
        tags=["Email Authentication"],
        request_body=PostUserSerializer,
        responses={200: "Success"},
    )
    def post(self, request):
        user_email = request.data.get("email")
        if not user_email:
            return Response(
                {"message": "Please enter your e-mail."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        random_code = "".join(
            random.choices(string.digits, k=6)
        )  # Generate 6-digit random string
        subject = "[HUMASCOT] Membership verification code"
        body = f"Email verification code: {random_code}"  # Add to random code body
        email = EmailMessage(
            subject,
            body,
            to=[user_email],
        )
        email.send()

        # Save authentication code to DB
        code = CheckEmail.objects.create(code=random_code, email=user_email)
        return Response(
            {"message": "Your email has been sent. Please check your mailbox."},
            status=status.HTTP_200_OK,
        )


class CheckEmailView(APIView):
    def post(self, request):
        # # Most recent authentication code instance
        # code_obj = (
        # CheckEmail.objects.filter(email=email).order_by("-created_at").first()
        # )
        # # Check after deployment
        code = request.data.get("code")
        email = request.data.get("email")
        code_obj = CheckEmail.objects.filter(email=email, code=code).first()
        if code_obj is None:
            return Response(
                {"message": "No verification code was sent to that email."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        tz = pytz.timezone("Asia/Vientiane")

        # If the authentication code has expired
        if code_obj.expires_at < datetime.now(tz=tz):
            code_obj.delete()
            return Response(
                {"message": "The verification code has expired."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        code_obj.delete()  # Delete email verification code
        return Response(
            {"message": "Email verification has been completed.", "is_checked": True},
            status=status.HTTP_200_OK,
        )


# join the membership
class SignupView(APIView):
    def get(self, request):
        user = request.user.is_authenticated
        if user:
            return redirect("/")
        else:
            param = request.GET.get("user_type")  # Parameter called ‘param_name’
            if not param:
                return render(
                    request,
                    "user/user_type_choice.html",
                )
            elif str(param) == "1":
                return render(
                    request,
                    "user/basic_signup.html",
                )
            elif str(param) == "2":
                return render(
                    request,
                    "user/seller_signup.html",
                )

    @swagger_auto_schema(
        tags=["join the membership"],
        request_body=PostUserSerializer,
        responses={200: "Success"},
    )
    def post(self, request):
        with transaction.atomic():
            category = request.data.get("category")
            email = request.data.get("email")
            code = request.data.get("code")
            password = request.data.get("password")
            password2 = request.data.get("password2")
            profile_image = request.data.get("profile_image")
            code_obj = CheckEmail.objects.filter(email=email, code=code).first()

            # Check whether the password and password match
            if password != password2:
                return JsonResponse(
                    {
                        "message": "Your password and password confirmation do not match."
                    },
                    status=status.HTTP_400_BAD_REQUEST,
                )

            # Check for email duplicates
            user = UserModel.objects.filter(email=email)
            if user.exists():
                return Response(
                    {"message": "The email already exists."},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            if code_obj is None:
                return Response(
                    {"message": "No verification code was sent to that email."},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            tz = pytz.timezone("Asia/Vientiane")

            # If the verification code has expired
            if code_obj.expires_at < datetime.now(tz=tz):
                code_obj.delete()
                return Response(
                    {"message": "The verification code has expired."},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            # Check if your email matches

            if profile_image == "undefined" or profile_image is None:
                # If the image comes as an empty value, use copy to change it!
                # deepcopy -> Import copy module? -> Complete copy! (safe)
                # Consider using try, except -> Additional exception handling!
                data = request.data.copy()
                data["profile_image"] = None
                serializer = UserSerializer(data=data)
            else:
                serializer = UserSerializer(data=request.data)
            if serializer.is_valid():
                """
                Add store-specific membership registration logic
                """
                if category != "2":
                    code_obj.delete()  # Delete email verification code
                    serializer.save()
                if category == "2":
                    name = request.data.get("name")
                    address = request.data.get("address")
                    if not name or not address:
                        return Response(
                            {"message": "Please enter all required information."},
                            status.HTTP_400_BAD_REQUEST,
                        )
                    sell_serializer = SellerSerializer(data=request.data)
                    code_obj.delete()  # Delete email verification code
                    if sell_serializer.is_valid():
                        serializer.save(is_seller=True)
                        sell_serializer.save(seller_id=serializer.data.get("id"))
                    else:
                        return Response(
                            {"message": f"{serializer.errors}"},
                            status=status.HTTP_400_BAD_REQUEST,
                        )

                return Response(
                    {"message": "Your registration has been completed."},
                    status=status.HTTP_201_CREATED,
                )
            else:
                return Response(
                    {"message": f"{serializer.errors}"},
                    status=status.HTTP_400_BAD_REQUEST,
                )


class RestaurantSignupView(APIView):
    @swagger_auto_schema(
        tags=["join the membership"],
        request_body=PostUserSerializer,
        responses={200: "Success"},
    )
    def post(self, request):
        with transaction.atomic():
            email = request.data.get("email")
            password = request.data.get("password")
            password2 = request.data.get("password2")
            profile_image = request.data.get("profile_image")

            # Check whether the password and password match
            if password != password2:
                return JsonResponse(
                    {
                        "message": "Your password and password confirmation do not match."
                    },
                    status=status.HTTP_400_BAD_REQUEST,
                )

            # Check for email duplicates
            user = UserModel.objects.filter(email=email)
            if user.exists():
                return Response(
                    {"message": "The email already exists."},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            if profile_image == "undefined" or profile_image is None:
                # If the image comes as an empty value, use copy to change it!
                # deepcopy -> Import copy module? -> Complete copy! (safe)
                # Consider using try, except -> Additional exception handling!
                data = request.data.copy()
                data["profile_image"] = None

templates/user/basic_signup.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
    <link rel="icon" href=""/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:locale" content="ko_KR"/>
    <meta property="og:site_name" content=""/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content=""/>
    <meta property="og:description" content=""/>
    <title></title>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content=""/>
    <meta property="og:title" content=""/>
    <meta property="og:description" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:locale" content="ko_KR"/>
    <link rel="stylesheet" href="{% static 'assets/css/common.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'assets/css/user.css' %}" type="text/css"/>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/user.js' %}"></script>
</head>

<body>
<div id="wrap" class="user">
    <div class="top_area">
        <button class="back" onclick="history.back()">Back</button>
    </div>
    <div class="title mt20">
        사용자 회원가입
        <small>사용자로 가입 진행 중이에요!</small>
    </div>
    <div class="form">
        <div class="input_wrap pr">
            <input id="email" type="email" class="ty01" placeholder="이메일"/>
            <div onclick="sendEmailCode()" id="email_send_btn" class="cert_btn">인증</div>
        </div>
        <div class="input_wrap mt10">
            <input id="code" type="text" class="ty01" placeholder="인증번호"/>
        </div>
        <div class="input_wrap mt10">
            <input
                    type="text"
                    class="ty01"
                    maxlength="10"
                    placeholder="닉네임(최대10자)"
                    id='nickname'
            />
        </div>
        <div class="input_wrap mt10">
            <input id='password' type="password" class="ty01" placeholder="비밀번호"/>
        </div>
        <div class="input_wrap mt10">
            <input id='password2' type="password" class="ty01" placeholder="비밀번호 확인"/>
        </div>
        <button id="loginButton" onclick="signUp()" class="btn mt30">확인</button>
        <div id="error_msg" class="error mt20" style="display: none;">
        </div>
    </div>
</div>
<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script>
    const inputFields = document.querySelectorAll(".form .ty01");
    inputFields.forEach(function (inputElement) {
        inputElement.addEventListener("input", function () {
            if (inputElement.value !== "") {
                inputElement.style.backgroundColor = "rgba(255,79,22,0.2)";
                inputElement.style.border = "none";
            } else {
                inputElement.style.backgroundColor = "initial";
                inputElement.style.border = "1px solid #dddce1";
            }
        });
    });
</script>
<script>
        // 인풋 입력시 버튼 온
    document.getElementById('email').addEventListener('input', checkInputs);
    document.getElementById('code').addEventListener('input', checkInputs);
    document.getElementById('nickname').addEventListener('input', checkInputs);
    document.getElementById('password').addEventListener('input', checkInputs);
    document.getElementById('password2').addEventListener('input', checkInputs);

    function checkInputs() {
        var email = document.getElementById('email').value;
        var code = document.getElementById('code').value;
        var nickname = document.getElementById('nickname').value;
        var password = document.getElementById('password').value;
        var password2 = document.getElementById('password2').value;
        var loginButton = document.getElementById('loginButton');

        if (email && password && code && nickname && password && password2) {
            // 이메일과 비밀번호가 모두 입력되었을 경우
            loginButton.classList.add('on');
        } else {
            // 입력되지 않은 필드가 있을 경우
            loginButton.classList.remove('on');
        }
    }
</script>
</body>
</html>

templates/user/change_seller.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
    <link rel="icon" href=""/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:locale" content="ko_KR"/>
    <meta property="og:site_name" content=""/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content=""/>
    <meta property="og:description" content=""/>
    <title></title>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content=""/>
    <meta property="og:title" content=""/>
    <meta property="og:description" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:locale" content="ko_KR"/>
    <link rel="stylesheet" href="{% static 'assets/css/common.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'assets/css/user.css' %}" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
</head>

<body>
<div id="wrap" class="user">
    <div class="top_area">
        <button class="back" onclick="history.back()">Back</button>
    </div>
    <div class="title mt20">
        판매자 추가정보
        <small>판매자 등록을 위해 추가 정보를 입력해 주세요!</small>
    </div>
    <div class="form">
        <div class="s_title">추가 정보 입력</div>
        <div class="input_wrap mt10 pr">
            <input id='name' type="text" class="ty01" placeholder="상점 이름(필수)"/>
        </div>
        <div class="error mt10">
            한번 설정한 상점 이름은 변경 할 수 없습니다.
        </div>
        <div class="input_wrap mt10 pr">
            <input id='address' type="text" class="ty01 pdr postcodify_address" placeholder="주소(필수)" readonly/>
            <div class="cert_btn" id="postcodify_search_button">검색</div>
        </div>
        <div class="input_wrap mt10 pr">
            <input id='sub_address' type="text" class="ty01 pdr" placeholder="상세 주소(선택)"/>
        </div>
        <div class="input_wrap mt10">
            <input id='phone' type="text" class="ty01" placeholder="연락처(선택)"/>
        </div>
        <div class="input_wrap mt10">
            <input
                    type="text"
                    class="ty01"
                    placeholder="사업자등록번호(선택)"
                    id='company_number'
            />
        </div>
        <div class="input_wrap mt10">
            <textarea
                    name=""
                    class="ty01"
                    placeholder="상점 소개(선택/최대 300자)"
                    maxlength="300"
                    id='introduce'
            ></textarea>
        </div>
        <button id="loginButton" onclick="sellerChange()" class="btn mt30">확인</button>
        <div id="error_msg" class="error mt20" style="display: none;">
        </div>
    </div>
</div>
<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script src="//d1p7wdleee1q2z.cloudfront.net/post/search.min.js"></script>
<script>
    const inputFields = document.querySelectorAll(".form .ty01");
    inputFields.forEach(function (inputElement) {
        inputElement.addEventListener("input", function () {
            if (inputElement.value !== "") {
                inputElement.style.backgroundColor = "rgba(255,79,22,0.2)";
                inputElement.style.border = "none";
            } else {
                inputElement.style.backgroundColor = "initial";
                inputElement.style.border = "1px solid #dddce1";
            }
        });
    });
</script>
<script>
    $(function () {
        // 포에시스 주소 api
        $("#postcodify_search_button").postcodifyPopUp();
    });
</script>
<script>
    async function sellerChange() {
        let data = {
            'name': document.getElementById('name').value,
            'phone': document.getElementById('phone').value,
            'address': document.getElementById('address').value,
            'sub_address': document.getElementById('sub_address').value,
            'company_number': document.getElementById('company_number').value,
            'introduce': document.getElementById('introduce').value,
            'user_id': localStorage.getItem('user_id')  //요청시 필요한 토큰 값
        };
        console.log(data)
        const response = await fetch(`${backend_base_url}/user/seller-signup`, {
            headers: {
                'content-type': 'application/json',
            },
            body: JSON.stringify(data),
            method: 'POST',
        });
        let response_json = await response.json()
        console.log(response_json)
        if (response.ok) {
            localStorage.setItem("user_id", response_json['user_id'])
            localStorage.setItem("user_name", response_json['user_name'])
            localStorage.setItem("origin_store_name", response_json['origin_store_name'])
            localStorage.setItem("image", response_json['image'])
            localStorage.setItem("email", response_json['email'])
            if (response_json['store_id']) {
                localStorage.setItem("store_id", response_json['store_id'])
            }
            window.location.href = '/store/goods/list';
        } else if (response_json['message']) {
            document.getElementById('error_msg').innerText = response_json['message']
            document.getElementById('error_msg').style.display = 'block'
        }
    };
</script>
<script>
    // 인풋 입력시 버튼 온
    document.getElementById('name').addEventListener('input', checkInputs);

    function checkInputs() {
        var name = document.getElementById('name').value;
        // 주소 팝업이라 이벤트 적용 X
        var loginButton = document.getElementById('loginButton');

        if (name) {
            loginButton.classList.add('on');
        } else {
            // 입력되지 않은 필드가 있을 경우
            loginButton.classList.remove('on');
        }
    }
</script>
</body>
</html>

templates/user/my_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/user.js' %}"></script>
    <title>Title</title>
</head>
<body>
<h1>마이 페이지</h1>
<div id="user_info"></div>
<div id="store_info"></div>
</div>
</body>
</html>

templates/user/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
    <link rel="icon" href=""/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:locale" content="ko_KR"/>
    <meta property="og:site_name" content=""/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content=""/>
    <meta property="og:description" content=""/>
    <title></title>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content=""/>
    <meta property="og:title" content=""/>
    <meta property="og:description" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:locale" content="ko_KR"/>
    <link rel="stylesheet" href="{% static 'assets/css/common.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'assets/css/user.css' %}" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/user.js' %}"></script>
</head>

<body>
<div id="wrap" class="user login">
    <div class="title">
        로그인
        <small>서비스 이용을 위해 로그인을 진행해 주세요!</small>
    </div>
    <div class="form">
        <div class="input_wrap pr">
            <input type="email" class="ty01" autocomplete='off' placeholder="이메일" id="email"/>
            <label for="email" class="ty01">Email</label>
        </div>
        <div class="input_wrap pr mt30">
            <input type="password" autocomplete='off' class="ty01" placeholder="비밀번호" id='password'/>
            <label for="" class="ty01">Password</label>
        </div>
        <div id="error_msg" class="error mt20" style="display: none;">
        </div>
        <div class="find_pw mt30">
            비밀번호를 잊으셨나요? <a href="/user/find">비밀번호 찾기</a>
        </div>
        <button id="loginButton" class="btn mt30" onclick="logIn()">로그인</button>
        <div class="join mt30">
            처음이신가요? <a href="/user/signup">회원가입</a>
        </div>
        <div class="sns mt50">
            SNS 계정으로 간편 가입하기
{#            <a href="{% url 'users:social_login' %}">구글회원가입</a>#}
            <a onclick="googleUrl()">구글회원가입</a>
        </div>
    </div>
</div>
<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script>
    const inputFields = document.querySelectorAll(".form .ty01");
    inputFields.forEach(function (inputElement) {
        inputElement.addEventListener("input", function () {
            if (inputElement.value !== "") {
                inputElement.style.backgroundColor = "rgba(255,79,22,0.2)";
                inputElement.style.border = "none";
            } else {
                inputElement.style.backgroundColor = "initial";
                inputElement.style.border = "1px solid #dddce1";
            }
        });
    });
</script>
<script>
    // 인풋 입력시 버튼 온
    document.getElementById('email').addEventListener('input', checkInputs);
    document.getElementById('password').addEventListener('input', checkInputs);

    function checkInputs() {
        var email = document.getElementById('email').value;
        var password = document.getElementById('password').value;
        var loginButton = document.getElementById('loginButton');

        if (email && password) {
            // 이메일과 비밀번호가 모두 입력되었을 경우
            loginButton.classList.add('on');
        } else {
            // 입력되지 않은 필드가 있을 경우
            loginButton.classList.remove('on');
        }
    }
</script>
</body>
</html>